mu: Add a new tool to show memory usage of files
mu is a new tool which shows the amount of data that a set of files
are keeping into the cache.
mu uses the new cachestat() syscall introduced with Linux 6.5.

Example usage, we use mu over gcc libraries, before and after calling
gcc for the first time after boot:

	$ mu --all --human-readable --threshold=1 /usr/lib/gcc/

	$ gcc /dev/null -o /dev/zero
	/usr/bin/ld: /usr/lib64/crt1.o: in function `__wrap_main':
	(.text+0x38): undefined reference to `main'
	collect2: error: ld returned 1 exit status

	$ mu --all --human-readable --threshold=1 /usr/lib/gcc/
	4.0K    /usr/lib/gcc/aarch64-redhat-linux/14/crtbegin.o
	4.0K    /usr/lib/gcc/aarch64-redhat-linux/14/crtend.o
	128K    /usr/lib/gcc/aarch64-redhat-linux/14/libgcc.a
	4.0K    /usr/lib/gcc/aarch64-redhat-linux/14/libgcc_s.so
	140K    /usr/lib/gcc/aarch64-redhat-linux/14
	140K    /usr/lib/gcc/aarch64-redhat-linux
	140K    /usr/lib/gcc/

Co-authored-by: Matteo Croce <teknoraver@meta.com>